name: Development and Production CI/CD

on:
  push:
    branches:
      - development
      - production
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        # replace this with your test command
        echo "Running tests"
        # pytest

  deploy-to-development:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Development Environment
      run: |
        echo "Deploying to development environment..."
        # Add your deployment command/script here

  deploy-to-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Production Environment
      run: |
        echo "Deploying to production environment..."
        # Add your deployment command/script here
